#services:
#  linkme-scheduler:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    networks:
#      - network-example

networks:
  network-example:
    external: true
#services:
#  mssql:
#    image: mcr.microsoft.com/mssql/server:2022-latest
#    environment:
#    - ACCEPT_EULA=yes
#    - MSSQL_PID=express
#    - MSSQL_SA_PASSWORD=JobsDB_Password
#    ports:
#    - 1434:1433
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
#    container_name: elasticsearch-instruments
#    environment:
#      - xpack.security.enabled=false
#      - discovery.type=single-node
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#      nofile:
#        soft: 65536
#        hard: 65536
#    cap_add:
#      - IPC_LOCK
#    volumes:
#      - elasticsearch-data:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200
#      - 9300:9300
#  kibana:
#    container_name: kibana-instruments
#    image: docker.elastic.co/kibana/kibana:7.8.0
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    ports:
#      - 5601:5601
#    depends_on:
#      - elasticsearch
#  zookeeper:
#    image: confluentinc/cp-zookeeper:latest
#    container_name: zookeeper
#    environment:
#      ZOOKEEPER_SERVER_ID: 1
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    ports:
#      - "22181:2181"
#
#  broker:
#    image: confluentinc/cp-kafka:latest
#    container_name: broker
#    ports:
#      - "9092:9092"
#    depends_on:
#      - zookeeper
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
##  rabbit:
##    image: "rabbitmq:3.7-management-alpine"
##    volumes:
##      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
##    ports:
##      - 5672:5672
##      - 15672:15672
#
#volumes:
#  elasticsearch-data:
#    driver: local
